### ISSUE TITLE
複数レコードの保存はすべきではないのでしょうか

### ISSUE THREAD

**Issue by logicoffee** [logicoffee/carta_tournaments#12]
現在`PlayersController`では複数レコードの保存が(無理やりですが)できるようになっています.
しかしコントローラにロジックが多く存在するのはあまり良くなさそうです.
ここに, `tournament_class`とのassociationも保存するとなったら大変なことになりそうです.

調べてみると, Form Objectなるものを作るパターンがあるみたいですね.
最終的には複数レコードの保存に対応できるようにはしたいですが, まずは単一レコードの保存機能を作るのがよいでしょうか？

**Comment by yubessy** [comment]
> まずは単一レコードの保存機能を作るのがよい

これが良いと思います。

複数レコードの保存や編集がしたい場合、フロントエンドではリスト形式のフォームを作ってリストの１項目毎に保存ボタンをつけておき、保存ボタンを押すとAjaxでサーバサイドのAPIを叩くようにしておけば、サーバサイドには単一レコード用のAPIだけあれば済みます。

一般的に、同じモデルのレコードをサーバサイドで一括CRUDすることが本当に必要なケースってあまりないのですよね。
銀行とかで一連の取引をひとつのトランザクションにまとめたい場合などは考えられますが・・・

**Comment by logicoffee** [comment]
Ajax, なるほど！
ひとまず無駄な機能を削除して単一レコードを保存できるようにします！
