### ISSUE TITLE
今後の開発について

### ISSUE THREAD

**Issue by logicoffee** [logicoffee/carta_tournaments#19]
細かい修正はあると思いますが, 最低限の機能は実装できたのではないかと思います.
今後優先して取り組むべきことは何でしょうか.
テストの追加や, 運営に向けての準備でしょうか？

`tournament_divisions`テーブルは作っただけになっていますが, 仕様が曖昧なため, それよりはもっとやるべきことに取り組みたいです！

**Comment by yubessy** [comment]
> 運営に向けての準備

これに一番力をいれましょう！

アプリケーションは使ってもらってなんぼです。まずは身近な大会運営関係者に使い勝手を試してもらい、フィードバックをもらって、可能な範囲で改善を進めていきましょう。

**Comment by logicoffee** [comment]
デプロイですが, ステージング等については特に考える必要はないですか？

**Comment by yubessy** [comment]
あったほうが便利だと思いますが、必須ではないです。簡単にprd/stgの2系統を立てられそうならやってみましょう。

**Comment by logicoffee** [comment]
ステージング環境が構築できました.
https://carta-tournaments-staging.herokuapp.com

今後修正がある場合は
- PR作成
- masterブランチにマージ
- herokuにプッシュ
という流れでやっていけばよいでしょうか？

**Comment by yubessy** [comment]
ちょっと忙しくて返事遅れていました。
はい、それでいいと思います！
