### ISSUE TITLE
文字コードについて

### ISSUE THREAD

**Issue by logicoffee** [logicoffee/carta_tournaments#24]
フォームから環境依存文字を入力しても, アプリが止まってしまわないのか.
という指摘を受けました.

どのタイミングで問題が発生するかがよく分かっていないため, 何をチェックすればいいかがあやふやです.
herokuのDB(Postgre)がUTF-8であることは確認できました.
あとは何をチェックすべきでしょうか？

**Comment by logicoffee** [comment]
文字コードについてもう一つあります.
UTF-8NでエンコーディングされたCSVをExcelで開くと文字化けするようです.
選択肢としてはShift_JISかBOMありUTF-8のどちらかだと思うのですが, 後者を選択すればよいでしょうか？

**Comment by yubessy** [comment]
> フォームから環境依存文字を入力しても, アプリが止まってしまわないのか.

内部的な挙動をコード上で調査する前に、まずはステージング環境等で試してしてみましょう。
Windows環境のIE等から、機種依存文字を含む文字列をフォームの学校名等に入力してみて、それの結果を他の環境で閲覧してみると良いと思います。

なお、現在の設定であればおそらく Ruby, ActiveRecord, PostgreSQL のどのレイヤでも、機種依存文字によりアプリケーションが不具合を起こすことはないと思います。

**Comment by yubessy** [comment]
> UTF-8NでエンコーディングされたCSVをExcelで開くと文字化けするようです.

アプリケーション側でUTF-8以外の文字コードに対応するのにも手間がかかるので、できればExcel側で「データの取り込み」機能を使ってもらいたいところですが・・・
http://primarytext.jp/blog/1275

どうしてもアプリケーション側で対応してほしいということであれば、CSV出力時のみShift-JISを使うのが良いと思います。
UTF-8 with BOM は UTF-8 と混同されやすく、また Shift-JIS よりも利用例が少ないので、Shift-JISのほうがまだ無難という印象です。

**Comment by logicoffee** [comment]
前者について, WindowsのIEから環境依存文字を入力してみましたが, 問題ありませんでした.

後者については問題なくできそうなので, これにてIssueをクローズします.
