### ISSUE TITLE
DBのバックアップについて

### ISSUE THREAD

**Issue by logicoffee** [logicoffee/carta_tournaments#25]
herokuのPGには定期バックアップの機能があるようです.

https://devcenter.heroku.com/articles/heroku-postgres-backups#scheduling-backups

DBのバックアップはメールにて行うということでしたが, この機能を使うというのでもよいのでしょうか？

`pg_dump`や`psql`等のコマンドを実行するにはパスワードが必要なのですが, 引数に渡すことはできず, 対話的に入力する必要があります.
これを避けるには環境変数`PGPASSWORD`を設定するか, ホームディレクトリに`.pgpass`を置くかのどちらかのようです.
https://www.postgresql.jp/document/9.2/html/libpq-envars.html

そうするくらいなら, 既に用意されている機能を使うのがよさそうだと感じました.

**Comment by yubessy** [comment]
今回のシステムの場合、バックアップの目的 (=データ消失の原因) は主に2つあります。

1. データベース自体の破損によるデータ消失を防ぐ
2. バグやヒューマンエラーによる誤ったデータの削除を防ぐ

DB全体のスナップショットによるバックアップについては主に1が対象となりますが、それだけではスナップショットの設定ミスやスナップショットそのものの誤った削除への対応にはなりません。

なので、HerokuのDBバックアップ機能を使うのはもちろんですが、大会管理者に日次で参加者一覧のCSVをメールで送る機能もあったほうが良いとは思います。

**Comment by logicoffee** [comment]
ひとつめの理由しか考えられてませんでした...

毎朝, 参加者一覧をCSVにまとめて送るというようにしたいと思います.
